#!/bin/sh

# Changes to: /script/directory/server
# This handles a case where the script would fail if it were executed with a
# working directory outside of its own directory.
cd "$( dirname "${BASH_SOURCE[0]}" )/server"
exec fresh
